server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: plop
      # uri : mongodb: //localhost:27017/plop
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: plop
kafka:
  topic:
    name: dm-message

token:
  # 1분
  access_expired_time: 600000
  secret_key: plip
  # 1시간
  refresh_expired_time: 3600000